services:
  backend:
    build: .
    ports:
      - "8080:8080"
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./soccer-player-app:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
